const LOGIN_USER = "LOGIN_USER";
const ADD_EVENT_ITEM = "ADD_EVENT_ITEM";
const DELETE_EVENT_ITEM = "DELETE_EVENT_ITEM";

module.exports = {
    LOGIN_USER,
    ADD_EVENT_ITEM,
    DELETE_EVENT_ITEM
};